### ISSUE TITLE
record linkage using textreuse

### ISSUE THREAD

**Issue by bihappywater** [ropensci/textreuse#85] opened 2019-03-28 15:08 UTC
Hi, 
I am new to textreuse package and find it is very userful. However, I would like to know is there any easier way to do the record linkage using textreuse package, when I have known already the reference data.  Example:
I have a list of text message, and I want to link them with my reference term
message
                   **message**
1              this is apple
2       this apple is delicious
3  this pineapple looks good
4       can i find stawberry
5    I like to eat chocolate
6               food is good

I want to find the "linkage" or match with provided list of term
7                   apple
8                 chocolate
9                     food

So ideal results should be
     message   --------------search_term
1              this is apple -----------                         7    apple
2       this apple is delicious  ---------                    7    apple
3  this pineapple looks good  -----------               NA
4       can i find stawberry -------------                    NA
5    I like to eat chocolate  -----------                   8    chocolate
6               food is good   -----------                     9     food

To achieve this, I tried following code, but it is not successful, 

```
docu <- data.frame(message= c("this is apple", "this apple is delicious", 
                                  "this pineapple looks good", "can i find stawberry",
                                  "I like to eat chocolate", "food is good"))

search_docu <- data.frame(message= c("apple", "chocolate", "food"))

dat<- rbind(docu, search_docu)%>% rowid_to_column()


minhash <- minhash_generator(n = 240, seed = 02082018)
# build the corpus using textreuse
docs <- apply(dat, 1, function(x) paste(x[-1], collapse = " ")) 
names(docs)<- dat$rowid
corpus <- TextReuseCorpus(text = docs, 
                          tokenizer =  tokenize_words,
                          progress = FALSE, 
                          keep_tokens = TRUE, 
                          minhash_func = minhash, 
                          skip_short = F  
) 

buckets <- lsh(corpus, bands = 10, progress = FALSE)

# grab candidate pairs
candidates <- lsh_candidates(buckets)
# get Jaccard similarities only for candidates
lsh_jaccard <- lsh_compare(candidates, corpus, jaccard_similarity, progress = FALSE)

lsh_df<- lsh_jaccard %>% mutate(a=as.numeric(a),b=as.numeric(b)) %>% as.data.frame()%>% 
  left_join(dat, by = c("a"="rowid")) %>%
  left_join(dat, by = c("b"="rowid")) 

```
Now I have two questions:
1. what is wrong with this code?
2. Even above approach is correct, but it is not the most efficient way! It doesn't make sense to compare between "this is apple" and "this apple is delicious". In a very large dataset, it is extremely expensive to compute.

Any suggestion?  Thanks a lot!

**Comment by lmullen** [comment] 2019-03-28 15:11
Closing because this is not a bug report. I am not able to provide support for applying the package to specific data analysis problems.

**Closed by lmullen** 2019-03-28 15:11 UTC
